### ISSUE TITLE
加载BridgingSkin 方块皮肤插件时报错

### ISSUE THREAD

**Issue by LSDogX** [SakuraKoi/BridgingAnalyzer#12]
换了v28的插件后在加载方块皮肤插件的时候报错了QwQ

[12:33:52 WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: sakura/kooi/BridgingAnalyzer/Utils/Metrics$CustomChart
[12:33:52 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135)
[12:33:52 WARN]:        at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.loadPlugin(PerWorldPluginLoader.java:160)
[12:33:52 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
[12:33:52 WARN]:        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:356)
[12:33:52 WARN]:        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
[12:33:52 WARN]:        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[12:33:52 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:33:52 WARN]:        at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95)
[12:33:52 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[12:33:52 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[12:33:52 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[12:33:52 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[12:33:52 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[12:33:52 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[12:33:52 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[12:33:52 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[12:33:52 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[12:33:52 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[12:33:52 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[12:33:52 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[12:33:52 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[12:33:52 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:33:52 WARN]: Caused by: java.lang.NoClassDefFoundError: sakura/kooi/BridgingAnalyzer/Utils/Metrics$CustomChart
[12:33:52 WARN]:        at java.lang.Class.forName0(Native Method)
[12:33:52 WARN]:        at java.lang.Class.forName(Unknown Source)
[12:33:52 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64)
[12:33:52 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
[12:33:52 WARN]:        ... 21 more
[12:33:52 WARN]: Caused by: java.lang.ClassNotFoundException: sakura.kooi.BridgingAnalyzer.Utils.Metrics$CustomChart
[12:33:52 WARN]:        at java.net.URLClassLoader.findClass(Unknown Source)
[12:33:52 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[12:33:52 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[12:33:52 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[12:33:52 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[12:33:52 WARN]:        ... 25 more

**Comment by SakuraKoi** [comment]
此错误不应该发生, 请尝试在没有PerWorldPlugin插件的服务端环境下运行试试

**Comment by SakuraKoi** [comment]
另外你这日志里炸了的是BridgingAnalyzer啊, 到底是加载哪个的时候出错的

**Comment by LSDogX** [comment]
确实是加载方块皮肤的时候出错的
我刚刚发现自己编译的时候用的是java 8，可能是这个的原因
一会我再试试，打扰您了

**Comment by SakuraKoi** [comment]
可以用java8编译, 我没有用新版本的特性, 只不过我这边jdk是11而已

**Comment by LSDogX** [comment]
好的，非常感谢

**Comment by SakuraKoi** [comment]
archived due to inactive
