### ISSUE TITLE
BlockSkinProvider Issues

### ISSUE THREAD

**Issue by Maroon28** [SakuraKoi/BridgingAnalyzer#16]
I've added Spigot and lombok to the build path, but I cannot seem to get specific functions to work such as `getPlacedBlocks`? What else am I supposed to build with?

**Comment by Maroon28** [comment]
> I've added Spigot and lombok to the build path, but I cannot seem to get specific functions to work such as `getPlacedBlocks`? What else am I supposed to build with?

Okay, so I fixed this but I have another issue with compilation. 

org.bukkit.plugin.InvalidPluginException: java.lang.Error: Unresolved compilation problems: 
        The import lombok cannot be resolved
        The import lombok cannot be resolved
        The import sakura.kooi.BridgingAnalyzer.api cannot be resolved
        Getter cannot be resolved to a type
        Getter cannot be resolved to a type
        Getter cannot be resolved to a type
        BlockSkinProvider cannot be resolved to a type
        BlockSkinProvider cannot be resolved to a type
        Setter cannot be resolved to a type
        BlockSkinProvider cannot be resolved to a type
        BlockSkinProvider cannot be resolved to a type
        BlockSkinProvider cannot be resolved to a type
        BlockSkinProvider cannot be resolved to a type

        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.4.jar:git-Paper-323]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.4.jar:git-Paper-323]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.4.jar:git-Paper-323]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.4.jar:git-Paper-323]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.4.jar:git-Paper-323]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.4.jar:git-Paper-323]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-323]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.Error: Unresolved compilation problems: 
        The import lombok cannot be resolved
        The import lombok cannot be resolved
        The import sakura.kooi.BridgingAnalyzer.api cannot be resolved
        Getter cannot be resolved to a type
        Getter cannot be resolved to a type
        Getter cannot be resolved to a type
        BlockSkinProvider cannot be resolved to a type
        BlockSkinProvider cannot be resolved to a type
        Setter cannot be resolved to a type
        BlockSkinProvider cannot be resolved to a type
        BlockSkinProvider cannot be resolved to a type
        BlockSkinProvider cannot be resolved to a type
        BlockSkinProvider cannot be resolved to a type

        at sakura.kooi.BridgingAnalyzer.BridgingAnalyzer.<init>(BridgingAnalyzer.java:3) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at java.lang.Class.newInstance(Class.java:584) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:91) ~[patched_1.16.4.jar:git-Paper-323]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.4.jar:git-Paper-323]
        ... 7 more

**Comment by SakuraKoi** [comment]
Your plugin Jar file did not compile successfully, eclipse replaces all compile failed method bodies with a simple throw while exporting jar file.
Follow https://projectlombok.org/setup/eclipse to install lombok into your eclipse IDE, then compile it again.

**Comment by SakuraKoi** [comment]
Also, you're targeting 1.16.4, and this plugin is written for 1.8, so there are some changes that need to be made to compile successfully (eg: Material/Sound enums, NMS Reflection etc.)

**Comment by Maroon28** [comment]
> Also, you're targeting 1.16.4 and this plugin is written for 1.8, most of the code works, but there are still some changes that need to be made to compile successfully (e.g. Material/Sound enums, NMS Reflection, etc.).

I've already installed lombok correctly, it's just having issues recognizing the BlockSkinProvider for some reason. Also, yeah I know, I already changed most of the materials and sounds  `The import sakura.kooi.BridgingAnalyzer.api cannot be resolved`

**Comment by SakuraKoi** [comment]
Sorry, I'm not sure why this is happening and I can't help much, try refactoring the BlockSkinProvider class (like renaming the class or package name) to refresh the cache that may exist, or remove the import line and let eclipse's quick fix do the import and see if that helps.

**Comment by SakuraKoi** [comment]
Closed due to inactivity, reopen if there are any updates
